version: "3.9"
services:
        
    kitodo-app:
       image: markusweigelt/kitodo-production:3.4.1

       ports:
        - 8080:8080 

       volumes:
        - type: bind
          source: ./kitodo/.ssh/id_rsa
          target: /id_rsa
        - type: bind
          source: ./kitodo.sql # overwrite default 3.4.1 database
          target: /tmp/kitodo/kitodo.sql
        - ./kitodo/config_modules:/usr/local/kitodo

       environment:
        - KITODO_DB_HOST=kitodo-db
        - KITODO_DB_SQL
        - KITODO_ES_HOST=kitodo-es
        - KITODO_MQ_HOST=kitodo-mq
        - OCRD_MANAGER=ocrd-manager

       depends_on:
        - kitodo-db
        - kitodo-es
        - kitodo-mq

        
    kitodo-db:
        image: mysql:8.0.26

        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: kitodo
          MYSQL_USER: kitodo
          MYSQL_PASSWORD: kitodo

        ports:
          - 3306:3306    


    kitodo-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - cluster.name=kitodo
            - node.name=kitodo-1
            - xpack.security.enabled=false

        ports:
            - 9200:9200
            - 9300:9300    
            
            
    kitodo-mq:
        image: markusweigelt/activemq:latest
        
        ports:
           - 61616:61616
           - 8161:8161
           
        volumes:   
           - type: bind
             source: ./kitodo-activemq.xml
             target: /opt/activemq/conf/activemq.xml